name: Generate JSON Daily

on:
    push:
        branches:
            - main # Replace 'main' with your target branch
# on:
#     schedule:
#         - cron: "0 0 * * *" # Run every day at midnight UTC

jobs:
    generate-json:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Generate JSON
              run: node script.js # Replace with your script file name
