name: Generate JSON on Push

on:
    push:
        branches:
            - main # Replace 'main' with your target branch

jobs:
    generate-json:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 12 # Specify Node.js version 16

            - name: Install dependencies
              run: npm install

            - name: Generate JSON
              run: node script.js # Replace with your script file name
